spring.application.name=webportal
spring.datasource.url=jdbc:postgresql://localhost:5432/project01
spring.datasource.username=project01db
spring.datasource.password=project01db+
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.springframework.security=DEBUG

# Image upload 
spring.servlet.multipart.max-file-size=1MB
spring.servlet.multipart.max-request-size=1MB
app.allowed.file.types=image/jpeg,image/png

# Mailing Service (SAMPLE SERVER ONLY)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=noreplycabalerron@gmail.com
spring.mail.password=etci wgem rbuc idub
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


# Email expiration time
password.reset.token.expiration.minutes=60

# News Bulletin Configuration
spring.jackson.date-format=MM-dd-yyyy

# Add news configuration
news.file.upload-dir=workspace/webportal-rest/src/main/resources/static/images/News
news.default.image.folder.path=workspace/webportal-rest/src/main/resources/static/images/News/default-news-images
news.main.default.image-folder=/images/News/default-news-images/
news.default-image=images/News/defaultImage.jpeg
news.image-folder=/images/News/
news.date.format=yyyy-MM-dd'T'HH:mm:ss.SSS'Z'
news.allowed.file.types=image/jpeg,image/png
news.valid.image-extensions=.jpeg,.png
news.start-end-date-format=MM-dd-yyyy